// Package report holds the output formatters for `assess --report ...`.
package report

import (
	"bytes"
	"fmt"
	"sort"

	"github.com/sroberts/plumbline/pkg/acmm"
)

// Markdown renders an acmm.Report as a committable markdown document.
// Mirrors the TUI results screen content without ANSI / interactivity.
func Markdown(r acmm.Report) []byte {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# Plumbline Maturity Report\n\n")
	fmt.Fprintf(&buf, "- **Repo:** `%s`\n", r.Repo)
	fmt.Fprintf(&buf, "- **Scanned:** %s\n", r.ScannedAt)
	fmt.Fprintf(&buf, "- **Tool:** plumbline %s · signal-set %s\n\n",
		r.ToolVersion, r.SignalSetVersion)

	fmt.Fprintf(&buf, "## Verdict\n\n")
	fmt.Fprintf(&buf, "**Level %d — %s**\n\n", r.Verdict.Level, r.Verdict.Name)
	fmt.Fprintf(&buf, "| Level | Name | Score |\n")
	fmt.Fprintf(&buf, "|-------|------|-------|\n")
	for _, l := range []acmm.Level{
		acmm.LevelInstructed, acmm.LevelMeasured,
		acmm.LevelAdaptive, acmm.LevelSelfSustaining,
	} {
		score := r.Verdict.LevelScores[l]
		marker := ""
		switch {
		case l == r.Verdict.Level:
			marker = " ✓"
		case l == r.Verdict.Level+1:
			marker = " ← next"
		}
		fmt.Fprintf(&buf, "| L%d | %s | %.0f%%%s |\n", l, l.Name(), score*100, marker)
	}
	fmt.Fprintln(&buf)

	if len(r.Verdict.NextGap) > 0 {
		fmt.Fprintf(&buf, "## Next-level gap (to reach L%d)\n\n", r.Verdict.Level+1)
		for _, id := range r.Verdict.NextGap {
			fmt.Fprintf(&buf, "- [ ] `%s`\n", id)
		}
		fmt.Fprintln(&buf)
	}

	// Per-signal table, grouped by level.
	signalsByLevel := make(map[acmm.Level][]acmm.SignalResult)
	for _, s := range r.Signals {
		signalsByLevel[s.Level] = append(signalsByLevel[s.Level], s)
	}
	for _, l := range []acmm.Level{
		acmm.LevelInstructed, acmm.LevelMeasured,
		acmm.LevelAdaptive, acmm.LevelSelfSustaining,
	} {
		sigs := signalsByLevel[l]
		if len(sigs) == 0 {
			continue
		}
		sort.Slice(sigs, func(i, j int) bool { return sigs[i].ID < sigs[j].ID })
		fmt.Fprintf(&buf, "## L%d — %s\n\n", l, l.Name())
		fmt.Fprintln(&buf, "| Signal | Status | Score | Confidence |")
		fmt.Fprintln(&buf, "|--------|--------|-------|------------|")
		for _, s := range sigs {
			fmt.Fprintf(&buf, "| `%s` | %s | %.2f | %s |\n",
				s.ID, s.Status, s.Score, s.Confidence)
		}
		fmt.Fprintln(&buf)
	}

	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf, "_Generated by [plumbline](https://github.com/sroberts/plumbline)._")

	return buf.Bytes()
}
